# Generated by Django 4.2.7 on 2024-09-25 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_store", "0002_alter_blogpost_preview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="Активно"),
        ),
    ]
